// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: camera_control.proto
// Protobuf C++ Version: 6.31.1

#include "camera_control.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace octaneapi {

inline constexpr Vector3::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Vector3::Vector3(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Vector3_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Vector3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vector3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vector3DefaultTypeInternal() {}
  union {
    Vector3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vector3DefaultTypeInternal _Vector3_default_instance_;

inline constexpr CameraUpResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        up_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraUpResponse::CameraUpResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraUpResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraUpResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraUpResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraUpResponseDefaultTypeInternal() {}
  union {
    CameraUpResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraUpResponseDefaultTypeInternal _CameraUpResponse_default_instance_;

inline constexpr CameraUpRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        up_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraUpRequest::CameraUpRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraUpRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraUpRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraUpRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraUpRequestDefaultTypeInternal() {}
  union {
    CameraUpRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraUpRequestDefaultTypeInternal _CameraUpRequest_default_instance_;

inline constexpr CameraTargetResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        target_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraTargetResponse::CameraTargetResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraTargetResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraTargetResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraTargetResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraTargetResponseDefaultTypeInternal() {}
  union {
    CameraTargetResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraTargetResponseDefaultTypeInternal _CameraTargetResponse_default_instance_;

inline constexpr CameraTargetRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        target_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraTargetRequest::CameraTargetRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraTargetRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraTargetRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraTargetRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraTargetRequestDefaultTypeInternal() {}
  union {
    CameraTargetRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraTargetRequestDefaultTypeInternal _CameraTargetRequest_default_instance_;

inline constexpr CameraPositionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraPositionResponse::CameraPositionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraPositionResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraPositionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraPositionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraPositionResponseDefaultTypeInternal() {}
  union {
    CameraPositionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraPositionResponseDefaultTypeInternal _CameraPositionResponse_default_instance_;

inline constexpr CameraPositionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CameraPositionRequest::CameraPositionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CameraPositionRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraPositionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraPositionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraPositionRequestDefaultTypeInternal() {}
  union {
    CameraPositionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraPositionRequestDefaultTypeInternal _CameraPositionRequest_default_instance_;
}  // namespace octaneapi
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_camera_5fcontrol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_camera_5fcontrol_2eproto = nullptr;
const ::uint32_t
    TableStruct_camera_5fcontrol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::Vector3, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::Vector3, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::octaneapi::Vector3, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::octaneapi::Vector3, _impl_.z_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraPositionRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraPositionRequest, _impl_.position_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraPositionResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraPositionResponse, _impl_.position_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraTargetRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraTargetRequest, _impl_.target_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraTargetResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraTargetResponse, _impl_.target_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraUpRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraUpRequest, _impl_.up_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraUpResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::octaneapi::CameraUpResponse, _impl_.up_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::octaneapi::Vector3)},
        {9, sizeof(::octaneapi::CameraPositionRequest)},
        {14, sizeof(::octaneapi::CameraPositionResponse)},
        {19, sizeof(::octaneapi::CameraTargetRequest)},
        {24, sizeof(::octaneapi::CameraTargetResponse)},
        {29, sizeof(::octaneapi::CameraUpRequest)},
        {34, sizeof(::octaneapi::CameraUpResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::octaneapi::_Vector3_default_instance_._instance,
    &::octaneapi::_CameraPositionRequest_default_instance_._instance,
    &::octaneapi::_CameraPositionResponse_default_instance_._instance,
    &::octaneapi::_CameraTargetRequest_default_instance_._instance,
    &::octaneapi::_CameraTargetResponse_default_instance_._instance,
    &::octaneapi::_CameraUpRequest_default_instance_._instance,
    &::octaneapi::_CameraUpResponse_default_instance_._instance,
};
const char descriptor_table_protodef_camera_5fcontrol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024camera_control.proto\022\toctaneapi\032\033googl"
    "e/protobuf/empty.proto\"*\n\007Vector3\022\t\n\001x\030\001"
    " \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"=\n\025CameraPosi"
    "tionRequest\022$\n\010position\030\001 \001(\0132\022.octaneap"
    "i.Vector3\">\n\026CameraPositionResponse\022$\n\010p"
    "osition\030\001 \001(\0132\022.octaneapi.Vector3\"9\n\023Cam"
    "eraTargetRequest\022\"\n\006target\030\001 \001(\0132\022.octan"
    "eapi.Vector3\":\n\024CameraTargetResponse\022\"\n\006"
    "target\030\001 \001(\0132\022.octaneapi.Vector3\"1\n\017Came"
    "raUpRequest\022\036\n\002up\030\001 \001(\0132\022.octaneapi.Vect"
    "or3\"2\n\020CameraUpResponse\022\036\n\002up\030\001 \001(\0132\022.oc"
    "taneapi.Vector32\314\003\n\rCameraControl\022M\n\021Set"
    "CameraPosition\022 .octaneapi.CameraPositio"
    "nRequest\032\026.google.protobuf.Empty\022N\n\021GetC"
    "ameraPosition\022\026.google.protobuf.Empty\032!."
    "octaneapi.CameraPositionResponse\022I\n\017SetC"
    "ameraTarget\022\036.octaneapi.CameraTargetRequ"
    "est\032\026.google.protobuf.Empty\022J\n\017GetCamera"
    "Target\022\026.google.protobuf.Empty\032\037.octanea"
    "pi.CameraTargetResponse\022A\n\013SetCameraUp\022\032"
    ".octaneapi.CameraUpRequest\032\026.google.prot"
    "obuf.Empty\022B\n\013GetCameraUp\022\026.google.proto"
    "buf.Empty\032\033.octaneapi.CameraUpResponseB\002"
    "H\002b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_camera_5fcontrol_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_camera_5fcontrol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_camera_5fcontrol_2eproto = {
    false,
    false,
    930,
    descriptor_table_protodef_camera_5fcontrol_2eproto,
    "camera_control.proto",
    &descriptor_table_camera_5fcontrol_2eproto_once,
    descriptor_table_camera_5fcontrol_2eproto_deps,
    1,
    7,
    schemas,
    file_default_instances,
    TableStruct_camera_5fcontrol_2eproto::offsets,
    file_level_enum_descriptors_camera_5fcontrol_2eproto,
    file_level_service_descriptors_camera_5fcontrol_2eproto,
};
namespace octaneapi {
// ===================================================================

class Vector3::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Vector3>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Vector3, _impl_._has_bits_);
};

Vector3::Vector3(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Vector3_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.Vector3)
}
Vector3::Vector3(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Vector3& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Vector3_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Vector3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Vector3::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Vector3::~Vector3() {
  // @@protoc_insertion_point(destructor:octaneapi.Vector3)
  SharedDtor(*this);
}
inline void Vector3::SharedDtor(MessageLite& self) {
  Vector3& this_ = static_cast<Vector3&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Vector3::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Vector3(arena);
}
constexpr auto Vector3::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Vector3),
                                            alignof(Vector3));
}
constexpr auto Vector3::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Vector3_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Vector3::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Vector3>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Vector3::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&Vector3::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Vector3, _impl_._cached_size_),
          false,
      },
      &Vector3::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Vector3_class_data_ =
        Vector3::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Vector3::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Vector3_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Vector3_class_data_.tc_table);
  return Vector3_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Vector3::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Vector3, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Vector3_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::Vector3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(Vector3, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(Vector3, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(Vector3, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(Vector3, _impl_.x_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(Vector3, _impl_.y_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(Vector3, _impl_.z_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
void Vector3::InternalSwap(Vector3* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Vector3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraPositionRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraPositionRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraPositionRequest, _impl_._has_bits_);
};

CameraPositionRequest::CameraPositionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraPositionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraPositionRequest)
}
PROTOBUF_NDEBUG_INLINE CameraPositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraPositionRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraPositionRequest::CameraPositionRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraPositionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraPositionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraPositionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraPositionRequest)
}
PROTOBUF_NDEBUG_INLINE CameraPositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraPositionRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.position_ = {};
}
CameraPositionRequest::~CameraPositionRequest() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraPositionRequest)
  SharedDtor(*this);
}
inline void CameraPositionRequest::SharedDtor(MessageLite& self) {
  CameraPositionRequest& this_ = static_cast<CameraPositionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraPositionRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraPositionRequest(arena);
}
constexpr auto CameraPositionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraPositionRequest),
                                            alignof(CameraPositionRequest));
}
constexpr auto CameraPositionRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraPositionRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraPositionRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraPositionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraPositionRequest::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraPositionRequest::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraPositionRequest, _impl_._cached_size_),
          false,
      },
      &CameraPositionRequest::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraPositionRequest_class_data_ =
        CameraPositionRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraPositionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraPositionRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraPositionRequest_class_data_.tc_table);
  return CameraPositionRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraPositionRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraPositionRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraPositionRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraPositionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 position = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraPositionRequest, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 position = 1;
    {PROTOBUF_FIELD_OFFSET(CameraPositionRequest, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraPositionRequest::InternalSwap(CameraPositionRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraPositionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraPositionResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraPositionResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraPositionResponse, _impl_._has_bits_);
};

CameraPositionResponse::CameraPositionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraPositionResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraPositionResponse)
}
PROTOBUF_NDEBUG_INLINE CameraPositionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraPositionResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraPositionResponse::CameraPositionResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraPositionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraPositionResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraPositionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraPositionResponse)
}
PROTOBUF_NDEBUG_INLINE CameraPositionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraPositionResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.position_ = {};
}
CameraPositionResponse::~CameraPositionResponse() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraPositionResponse)
  SharedDtor(*this);
}
inline void CameraPositionResponse::SharedDtor(MessageLite& self) {
  CameraPositionResponse& this_ = static_cast<CameraPositionResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraPositionResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraPositionResponse(arena);
}
constexpr auto CameraPositionResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraPositionResponse),
                                            alignof(CameraPositionResponse));
}
constexpr auto CameraPositionResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraPositionResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraPositionResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraPositionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraPositionResponse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraPositionResponse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraPositionResponse, _impl_._cached_size_),
          false,
      },
      &CameraPositionResponse::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraPositionResponse_class_data_ =
        CameraPositionResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraPositionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraPositionResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraPositionResponse_class_data_.tc_table);
  return CameraPositionResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraPositionResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraPositionResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraPositionResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraPositionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 position = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraPositionResponse, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 position = 1;
    {PROTOBUF_FIELD_OFFSET(CameraPositionResponse, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraPositionResponse::InternalSwap(CameraPositionResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraPositionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraTargetRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraTargetRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraTargetRequest, _impl_._has_bits_);
};

CameraTargetRequest::CameraTargetRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraTargetRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraTargetRequest)
}
PROTOBUF_NDEBUG_INLINE CameraTargetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraTargetRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraTargetRequest::CameraTargetRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraTargetRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraTargetRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraTargetRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.target_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.target_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraTargetRequest)
}
PROTOBUF_NDEBUG_INLINE CameraTargetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraTargetRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.target_ = {};
}
CameraTargetRequest::~CameraTargetRequest() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraTargetRequest)
  SharedDtor(*this);
}
inline void CameraTargetRequest::SharedDtor(MessageLite& self) {
  CameraTargetRequest& this_ = static_cast<CameraTargetRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.target_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraTargetRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraTargetRequest(arena);
}
constexpr auto CameraTargetRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraTargetRequest),
                                            alignof(CameraTargetRequest));
}
constexpr auto CameraTargetRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraTargetRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraTargetRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraTargetRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraTargetRequest::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraTargetRequest::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraTargetRequest, _impl_._cached_size_),
          false,
      },
      &CameraTargetRequest::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraTargetRequest_class_data_ =
        CameraTargetRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraTargetRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraTargetRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraTargetRequest_class_data_.tc_table);
  return CameraTargetRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraTargetRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraTargetRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraTargetRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraTargetRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 target = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraTargetRequest, _impl_.target_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 target = 1;
    {PROTOBUF_FIELD_OFFSET(CameraTargetRequest, _impl_.target_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraTargetRequest::InternalSwap(CameraTargetRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraTargetRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraTargetResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraTargetResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraTargetResponse, _impl_._has_bits_);
};

CameraTargetResponse::CameraTargetResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraTargetResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraTargetResponse)
}
PROTOBUF_NDEBUG_INLINE CameraTargetResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraTargetResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraTargetResponse::CameraTargetResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraTargetResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraTargetResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraTargetResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.target_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.target_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraTargetResponse)
}
PROTOBUF_NDEBUG_INLINE CameraTargetResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraTargetResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.target_ = {};
}
CameraTargetResponse::~CameraTargetResponse() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraTargetResponse)
  SharedDtor(*this);
}
inline void CameraTargetResponse::SharedDtor(MessageLite& self) {
  CameraTargetResponse& this_ = static_cast<CameraTargetResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.target_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraTargetResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraTargetResponse(arena);
}
constexpr auto CameraTargetResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraTargetResponse),
                                            alignof(CameraTargetResponse));
}
constexpr auto CameraTargetResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraTargetResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraTargetResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraTargetResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraTargetResponse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraTargetResponse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraTargetResponse, _impl_._cached_size_),
          false,
      },
      &CameraTargetResponse::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraTargetResponse_class_data_ =
        CameraTargetResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraTargetResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraTargetResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraTargetResponse_class_data_.tc_table);
  return CameraTargetResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraTargetResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraTargetResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraTargetResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraTargetResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 target = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraTargetResponse, _impl_.target_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 target = 1;
    {PROTOBUF_FIELD_OFFSET(CameraTargetResponse, _impl_.target_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraTargetResponse::InternalSwap(CameraTargetResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraTargetResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraUpRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraUpRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraUpRequest, _impl_._has_bits_);
};

CameraUpRequest::CameraUpRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraUpRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraUpRequest)
}
PROTOBUF_NDEBUG_INLINE CameraUpRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraUpRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraUpRequest::CameraUpRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraUpRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraUpRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraUpRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.up_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.up_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraUpRequest)
}
PROTOBUF_NDEBUG_INLINE CameraUpRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraUpRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.up_ = {};
}
CameraUpRequest::~CameraUpRequest() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraUpRequest)
  SharedDtor(*this);
}
inline void CameraUpRequest::SharedDtor(MessageLite& self) {
  CameraUpRequest& this_ = static_cast<CameraUpRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.up_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraUpRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraUpRequest(arena);
}
constexpr auto CameraUpRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraUpRequest),
                                            alignof(CameraUpRequest));
}
constexpr auto CameraUpRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraUpRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraUpRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraUpRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraUpRequest::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraUpRequest::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraUpRequest, _impl_._cached_size_),
          false,
      },
      &CameraUpRequest::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraUpRequest_class_data_ =
        CameraUpRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraUpRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraUpRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraUpRequest_class_data_.tc_table);
  return CameraUpRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraUpRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraUpRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraUpRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraUpRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 up = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraUpRequest, _impl_.up_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 up = 1;
    {PROTOBUF_FIELD_OFFSET(CameraUpRequest, _impl_.up_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraUpRequest::InternalSwap(CameraUpRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraUpRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraUpResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CameraUpResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CameraUpResponse, _impl_._has_bits_);
};

CameraUpResponse::CameraUpResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraUpResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:octaneapi.CameraUpResponse)
}
PROTOBUF_NDEBUG_INLINE CameraUpResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::octaneapi::CameraUpResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CameraUpResponse::CameraUpResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CameraUpResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CameraUpResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraUpResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.up_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.up_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:octaneapi.CameraUpResponse)
}
PROTOBUF_NDEBUG_INLINE CameraUpResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CameraUpResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.up_ = {};
}
CameraUpResponse::~CameraUpResponse() {
  // @@protoc_insertion_point(destructor:octaneapi.CameraUpResponse)
  SharedDtor(*this);
}
inline void CameraUpResponse::SharedDtor(MessageLite& self) {
  CameraUpResponse& this_ = static_cast<CameraUpResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.up_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CameraUpResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CameraUpResponse(arena);
}
constexpr auto CameraUpResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CameraUpResponse),
                                            alignof(CameraUpResponse));
}
constexpr auto CameraUpResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CameraUpResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CameraUpResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CameraUpResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CameraUpResponse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CameraUpResponse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CameraUpResponse, _impl_._cached_size_),
          false,
      },
      &CameraUpResponse::kDescriptorMethods,
      &descriptor_table_camera_5fcontrol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CameraUpResponse_class_data_ =
        CameraUpResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CameraUpResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CameraUpResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CameraUpResponse_class_data_.tc_table);
  return CameraUpResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CameraUpResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CameraUpResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CameraUpResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::octaneapi::CameraUpResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .octaneapi.Vector3 up = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CameraUpResponse, _impl_.up_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .octaneapi.Vector3 up = 1;
    {PROTOBUF_FIELD_OFFSET(CameraUpResponse, _impl_.up_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::octaneapi::Vector3>()},
  }},
  {{
  }},
};
void CameraUpResponse::InternalSwap(CameraUpResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CameraUpResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace octaneapi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_camera_5fcontrol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
