# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apimoduledata.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'apimoduledata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pimoduledata.proto\x12\toctaneapi\x1a\x0c\x63ommon.proto\"\xcd\x02\n\rApiModuleData\x1a\x44\n\x1aloadApplicationDataRequest\x12&\n\x08moduleId\x18\x01 \x01(\x0b\x32\x14.octaneapi.ModuleIdT\x1aZ\n\x1bloadApplicationDataResponse\x12$\n\x06result\x18\x01 \x01(\x0b\x32\x14.octaneapi.ObjectRef\x12\x15\n\roctaneVersion\x18\x02 \x01(\r\x1aj\n\x1bstoreApplicationDataRequest\x12&\n\x08moduleId\x18\x01 \x01(\x0b\x32\x14.octaneapi.ModuleIdT\x12#\n\x05table\x18\x02 \x01(\x0b\x32\x14.octaneapi.ObjectRef\x1a.\n\x1cstoreApplicationDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x9f\x02\n\x14\x41piModuleDataService\x12\x80\x01\n\x13loadApplicationData\x12\x33.octaneapi.ApiModuleData.loadApplicationDataRequest\x1a\x34.octaneapi.ApiModuleData.loadApplicationDataResponse\x12\x83\x01\n\x14storeApplicationData\x12\x34.octaneapi.ApiModuleData.storeApplicationDataRequest\x1a\x35.octaneapi.ApiModuleData.storeApplicationDataResponseB\x02H\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apimoduledata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_APIMODULEDATA']._serialized_start=49
  _globals['_APIMODULEDATA']._serialized_end=382
  _globals['_APIMODULEDATA_LOADAPPLICATIONDATAREQUEST']._serialized_start=66
  _globals['_APIMODULEDATA_LOADAPPLICATIONDATAREQUEST']._serialized_end=134
  _globals['_APIMODULEDATA_LOADAPPLICATIONDATARESPONSE']._serialized_start=136
  _globals['_APIMODULEDATA_LOADAPPLICATIONDATARESPONSE']._serialized_end=226
  _globals['_APIMODULEDATA_STOREAPPLICATIONDATAREQUEST']._serialized_start=228
  _globals['_APIMODULEDATA_STOREAPPLICATIONDATAREQUEST']._serialized_end=334
  _globals['_APIMODULEDATA_STOREAPPLICATIONDATARESPONSE']._serialized_start=336
  _globals['_APIMODULEDATA_STOREAPPLICATIONDATARESPONSE']._serialized_end=382
  _globals['_APIMODULEDATASERVICE']._serialized_start=385
  _globals['_APIMODULEDATASERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
