// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: apidiagnostics.proto

#include "apidiagnostics.pb.h"
#include "apidiagnostics.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace octaneapi {

static const char* ApiDiagnosticsService_method_names[] = {
  "/octaneapi.ApiDiagnosticsService/diagnosticCommand",
};

std::unique_ptr< ApiDiagnosticsService::Stub> ApiDiagnosticsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ApiDiagnosticsService::Stub> stub(new ApiDiagnosticsService::Stub(channel, options));
  return stub;
}

ApiDiagnosticsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_diagnosticCommand_(ApiDiagnosticsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ApiDiagnosticsService::Stub::diagnosticCommand(::grpc::ClientContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiDiagnostics_diagnosticCommandRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_diagnosticCommand_, context, request, response);
}

void ApiDiagnosticsService::Stub::async::diagnosticCommand(::grpc::ClientContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiDiagnostics_diagnosticCommandRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_diagnosticCommand_, context, request, response, std::move(f));
}

void ApiDiagnosticsService::Stub::async::diagnosticCommand(::grpc::ClientContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_diagnosticCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiDiagnosticsService::Stub::PrepareAsyncdiagnosticCommandRaw(::grpc::ClientContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::octaneapi::ApiDiagnostics_diagnosticCommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_diagnosticCommand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiDiagnosticsService::Stub::AsyncdiagnosticCommandRaw(::grpc::ClientContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdiagnosticCommandRaw(context, request, cq);
  result->StartCall();
  return result;
}

ApiDiagnosticsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiDiagnosticsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiDiagnosticsService::Service, ::octaneapi::ApiDiagnostics_diagnosticCommandRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiDiagnosticsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->diagnosticCommand(ctx, req, resp);
             }, this)));
}

ApiDiagnosticsService::Service::~Service() {
}

::grpc::Status ApiDiagnosticsService::Service::diagnosticCommand(::grpc::ServerContext* context, const ::octaneapi::ApiDiagnostics_diagnosticCommandRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace octaneapi
#include <grpcpp/ports_undef.inc>

