// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: apilock.proto

#include "apilock.pb.h"
#include "apilock.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace octaneapi {

static const char* ApiLockService_method_names[] = {
  "/octaneapi.ApiLockService/create",
  "/octaneapi.ApiLockService/destroy",
  "/octaneapi.ApiLockService/enter",
  "/octaneapi.ApiLockService/tryEnter",
  "/octaneapi.ApiLockService/exit",
};

std::unique_ptr< ApiLockService::Stub> ApiLockService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ApiLockService::Stub> stub(new ApiLockService::Stub(channel, options));
  return stub;
}

ApiLockService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_create_(ApiLockService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_destroy_(ApiLockService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_enter_(ApiLockService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_tryEnter_(ApiLockService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_exit_(ApiLockService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ApiLockService::Stub::create(::grpc::ClientContext* context, const ::octaneapi::ApiLock_createRequest& request, ::octaneapi::ApiLock_createResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiLock_createRequest, ::octaneapi::ApiLock_createResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_create_, context, request, response);
}

void ApiLockService::Stub::async::create(::grpc::ClientContext* context, const ::octaneapi::ApiLock_createRequest* request, ::octaneapi::ApiLock_createResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiLock_createRequest, ::octaneapi::ApiLock_createResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_create_, context, request, response, std::move(f));
}

void ApiLockService::Stub::async::create(::grpc::ClientContext* context, const ::octaneapi::ApiLock_createRequest* request, ::octaneapi::ApiLock_createResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::octaneapi::ApiLock_createResponse>* ApiLockService::Stub::PrepareAsynccreateRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_createRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::octaneapi::ApiLock_createResponse, ::octaneapi::ApiLock_createRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::octaneapi::ApiLock_createResponse>* ApiLockService::Stub::AsynccreateRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_createRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ApiLockService::Stub::destroy(::grpc::ClientContext* context, const ::octaneapi::ApiLock_destroyRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiLock_destroyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_destroy_, context, request, response);
}

void ApiLockService::Stub::async::destroy(::grpc::ClientContext* context, const ::octaneapi::ApiLock_destroyRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiLock_destroyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_destroy_, context, request, response, std::move(f));
}

void ApiLockService::Stub::async::destroy(::grpc::ClientContext* context, const ::octaneapi::ApiLock_destroyRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_destroy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::PrepareAsyncdestroyRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_destroyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::octaneapi::ApiLock_destroyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_destroy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::AsyncdestroyRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_destroyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdestroyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ApiLockService::Stub::enter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_enterRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiLock_enterRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_enter_, context, request, response);
}

void ApiLockService::Stub::async::enter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_enterRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiLock_enterRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_enter_, context, request, response, std::move(f));
}

void ApiLockService::Stub::async::enter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_enterRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_enter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::PrepareAsyncenterRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_enterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::octaneapi::ApiLock_enterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_enter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::AsyncenterRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_enterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncenterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ApiLockService::Stub::tryEnter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_tryEnterRequest& request, ::octaneapi::ApiLock_tryEnterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiLock_tryEnterRequest, ::octaneapi::ApiLock_tryEnterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_tryEnter_, context, request, response);
}

void ApiLockService::Stub::async::tryEnter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_tryEnterRequest* request, ::octaneapi::ApiLock_tryEnterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiLock_tryEnterRequest, ::octaneapi::ApiLock_tryEnterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_tryEnter_, context, request, response, std::move(f));
}

void ApiLockService::Stub::async::tryEnter(::grpc::ClientContext* context, const ::octaneapi::ApiLock_tryEnterRequest* request, ::octaneapi::ApiLock_tryEnterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_tryEnter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::octaneapi::ApiLock_tryEnterResponse>* ApiLockService::Stub::PrepareAsynctryEnterRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_tryEnterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::octaneapi::ApiLock_tryEnterResponse, ::octaneapi::ApiLock_tryEnterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_tryEnter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::octaneapi::ApiLock_tryEnterResponse>* ApiLockService::Stub::AsynctryEnterRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_tryEnterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynctryEnterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ApiLockService::Stub::exit(::grpc::ClientContext* context, const ::octaneapi::ApiLock_exitRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::octaneapi::ApiLock_exitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_exit_, context, request, response);
}

void ApiLockService::Stub::async::exit(::grpc::ClientContext* context, const ::octaneapi::ApiLock_exitRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::octaneapi::ApiLock_exitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_exit_, context, request, response, std::move(f));
}

void ApiLockService::Stub::async::exit(::grpc::ClientContext* context, const ::octaneapi::ApiLock_exitRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_exit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::PrepareAsyncexitRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_exitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::octaneapi::ApiLock_exitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_exit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ApiLockService::Stub::AsyncexitRaw(::grpc::ClientContext* context, const ::octaneapi::ApiLock_exitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncexitRaw(context, request, cq);
  result->StartCall();
  return result;
}

ApiLockService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiLockService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiLockService::Service, ::octaneapi::ApiLock_createRequest, ::octaneapi::ApiLock_createResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiLockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiLock_createRequest* req,
             ::octaneapi::ApiLock_createResponse* resp) {
               return service->create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiLockService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiLockService::Service, ::octaneapi::ApiLock_destroyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiLockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiLock_destroyRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->destroy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiLockService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiLockService::Service, ::octaneapi::ApiLock_enterRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiLockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiLock_enterRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->enter(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiLockService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiLockService::Service, ::octaneapi::ApiLock_tryEnterRequest, ::octaneapi::ApiLock_tryEnterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiLockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiLock_tryEnterRequest* req,
             ::octaneapi::ApiLock_tryEnterResponse* resp) {
               return service->tryEnter(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApiLockService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApiLockService::Service, ::octaneapi::ApiLock_exitRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ApiLockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::octaneapi::ApiLock_exitRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->exit(ctx, req, resp);
             }, this)));
}

ApiLockService::Service::~Service() {
}

::grpc::Status ApiLockService::Service::create(::grpc::ServerContext* context, const ::octaneapi::ApiLock_createRequest* request, ::octaneapi::ApiLock_createResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ApiLockService::Service::destroy(::grpc::ServerContext* context, const ::octaneapi::ApiLock_destroyRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ApiLockService::Service::enter(::grpc::ServerContext* context, const ::octaneapi::ApiLock_enterRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ApiLockService::Service::tryEnter(::grpc::ServerContext* context, const ::octaneapi::ApiLock_tryEnterRequest* request, ::octaneapi::ApiLock_tryEnterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ApiLockService::Service::exit(::grpc::ServerContext* context, const ::octaneapi::ApiLock_exitRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace octaneapi

