// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: apinodegrapheditor.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_apinodegrapheditor_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_apinodegrapheditor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_apinodegrapheditor_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_apinodegrapheditor_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_apinodegrapheditor_2eproto;
namespace octaneapi {
class ApiNodeGraphEditor;
struct ApiNodeGraphEditorDefaultTypeInternal;
extern ApiNodeGraphEditorDefaultTypeInternal _ApiNodeGraphEditor_default_instance_;
class ApiNodeGraphEditor_addGraphRequest;
struct ApiNodeGraphEditor_addGraphRequestDefaultTypeInternal;
extern ApiNodeGraphEditor_addGraphRequestDefaultTypeInternal _ApiNodeGraphEditor_addGraphRequest_default_instance_;
class ApiNodeGraphEditor_createRequest;
struct ApiNodeGraphEditor_createRequestDefaultTypeInternal;
extern ApiNodeGraphEditor_createRequestDefaultTypeInternal _ApiNodeGraphEditor_createRequest_default_instance_;
class ApiNodeGraphEditor_createResponse;
struct ApiNodeGraphEditor_createResponseDefaultTypeInternal;
extern ApiNodeGraphEditor_createResponseDefaultTypeInternal _ApiNodeGraphEditor_createResponse_default_instance_;
class ApiNodeGraphEditor_destroyRequest;
struct ApiNodeGraphEditor_destroyRequestDefaultTypeInternal;
extern ApiNodeGraphEditor_destroyRequestDefaultTypeInternal _ApiNodeGraphEditor_destroyRequest_default_instance_;
class ApiNodeGraphEditor_setContentGraphRequest;
struct ApiNodeGraphEditor_setContentGraphRequestDefaultTypeInternal;
extern ApiNodeGraphEditor_setContentGraphRequestDefaultTypeInternal _ApiNodeGraphEditor_setContentGraphRequest_default_instance_;
class NodeGraphEditorArrayT;
struct NodeGraphEditorArrayTDefaultTypeInternal;
extern NodeGraphEditorArrayTDefaultTypeInternal _NodeGraphEditorArrayT_default_instance_;
}  // namespace octaneapi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace octaneapi {

// ===================================================================


// -------------------------------------------------------------------

class ApiNodeGraphEditor final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor) */ {
 public:
  inline ApiNodeGraphEditor() : ApiNodeGraphEditor(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor(const ApiNodeGraphEditor& from) : ApiNodeGraphEditor(nullptr, from) {}
  inline ApiNodeGraphEditor(ApiNodeGraphEditor&& from) noexcept
      : ApiNodeGraphEditor(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor& operator=(const ApiNodeGraphEditor& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor& operator=(ApiNodeGraphEditor&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor*>(
        &_ApiNodeGraphEditor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(ApiNodeGraphEditor& a, ApiNodeGraphEditor& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ApiNodeGraphEditor>(arena);
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor"; }

 protected:
  explicit ApiNodeGraphEditor(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor(::google::protobuf::Arena* arena, const ApiNodeGraphEditor& from);
  ApiNodeGraphEditor(::google::protobuf::Arena* arena, ApiNodeGraphEditor&& from) noexcept
      : ApiNodeGraphEditor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using createRequest = ApiNodeGraphEditor_createRequest;
  using createResponse = ApiNodeGraphEditor_createResponse;
  using destroyRequest = ApiNodeGraphEditor_destroyRequest;
  using setContentGraphRequest = ApiNodeGraphEditor_setContentGraphRequest;
  using addGraphRequest = ApiNodeGraphEditor_addGraphRequest;

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class NodeGraphEditorArrayT final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.NodeGraphEditorArrayT) */ {
 public:
  inline NodeGraphEditorArrayT() : NodeGraphEditorArrayT(nullptr) {}
  ~NodeGraphEditorArrayT() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NodeGraphEditorArrayT(
      ::google::protobuf::internal::ConstantInitialized);

  inline NodeGraphEditorArrayT(const NodeGraphEditorArrayT& from) : NodeGraphEditorArrayT(nullptr, from) {}
  inline NodeGraphEditorArrayT(NodeGraphEditorArrayT&& from) noexcept
      : NodeGraphEditorArrayT(nullptr, std::move(from)) {}
  inline NodeGraphEditorArrayT& operator=(const NodeGraphEditorArrayT& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeGraphEditorArrayT& operator=(NodeGraphEditorArrayT&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeGraphEditorArrayT& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeGraphEditorArrayT* internal_default_instance() {
    return reinterpret_cast<const NodeGraphEditorArrayT*>(
        &_NodeGraphEditorArrayT_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NodeGraphEditorArrayT& a, NodeGraphEditorArrayT& b) { a.Swap(&b); }
  inline void Swap(NodeGraphEditorArrayT* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeGraphEditorArrayT* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeGraphEditorArrayT* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<NodeGraphEditorArrayT>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NodeGraphEditorArrayT* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.NodeGraphEditorArrayT"; }

 protected:
  explicit NodeGraphEditorArrayT(::google::protobuf::Arena* arena);
  NodeGraphEditorArrayT(::google::protobuf::Arena* arena, const NodeGraphEditorArrayT& from);
  NodeGraphEditorArrayT(::google::protobuf::Arena* arena, NodeGraphEditorArrayT&& from) noexcept
      : NodeGraphEditorArrayT(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .octaneapi.ApiNodeGraphEditor data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  ::octaneapi::ApiNodeGraphEditor* mutable_data(int index);
  ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>* mutable_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>& _internal_data() const;
  ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>* _internal_mutable_data();
  public:
  const ::octaneapi::ApiNodeGraphEditor& data(int index) const;
  ::octaneapi::ApiNodeGraphEditor* add_data();
  const ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>& data() const;
  // @@protoc_insertion_point(class_scope:octaneapi.NodeGraphEditorArrayT)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NodeGraphEditorArrayT_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NodeGraphEditorArrayT& from_msg);
    ::google::protobuf::RepeatedPtrField< ::octaneapi::ApiNodeGraphEditor > data_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class ApiNodeGraphEditor_setContentGraphRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor.setContentGraphRequest) */ {
 public:
  inline ApiNodeGraphEditor_setContentGraphRequest() : ApiNodeGraphEditor_setContentGraphRequest(nullptr) {}
  ~ApiNodeGraphEditor_setContentGraphRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor_setContentGraphRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor_setContentGraphRequest(const ApiNodeGraphEditor_setContentGraphRequest& from) : ApiNodeGraphEditor_setContentGraphRequest(nullptr, from) {}
  inline ApiNodeGraphEditor_setContentGraphRequest(ApiNodeGraphEditor_setContentGraphRequest&& from) noexcept
      : ApiNodeGraphEditor_setContentGraphRequest(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor_setContentGraphRequest& operator=(const ApiNodeGraphEditor_setContentGraphRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor_setContentGraphRequest& operator=(ApiNodeGraphEditor_setContentGraphRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor_setContentGraphRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor_setContentGraphRequest* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor_setContentGraphRequest*>(
        &_ApiNodeGraphEditor_setContentGraphRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ApiNodeGraphEditor_setContentGraphRequest& a, ApiNodeGraphEditor_setContentGraphRequest& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor_setContentGraphRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor_setContentGraphRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor_setContentGraphRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiNodeGraphEditor_setContentGraphRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiNodeGraphEditor_setContentGraphRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor.setContentGraphRequest"; }

 protected:
  explicit ApiNodeGraphEditor_setContentGraphRequest(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor_setContentGraphRequest(::google::protobuf::Arena* arena, const ApiNodeGraphEditor_setContentGraphRequest& from);
  ApiNodeGraphEditor_setContentGraphRequest(::google::protobuf::Arena* arena, ApiNodeGraphEditor_setContentGraphRequest&& from) noexcept
      : ApiNodeGraphEditor_setContentGraphRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectPtrFieldNumber = 1,
    kGraphFieldNumber = 2,
  };
  // .octaneapi.ObjectRef objectPtr = 1;
  bool has_objectptr() const;
  void clear_objectptr() ;
  const ::octaneapi::ObjectRef& objectptr() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_objectptr();
  ::octaneapi::ObjectRef* mutable_objectptr();
  void set_allocated_objectptr(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_objectptr();

  private:
  const ::octaneapi::ObjectRef& _internal_objectptr() const;
  ::octaneapi::ObjectRef* _internal_mutable_objectptr();

  public:
  // .octaneapi.ObjectRef graph = 2;
  bool has_graph() const;
  void clear_graph() ;
  const ::octaneapi::ObjectRef& graph() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_graph();
  ::octaneapi::ObjectRef* mutable_graph();
  void set_allocated_graph(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_graph(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_graph();

  private:
  const ::octaneapi::ObjectRef& _internal_graph() const;
  ::octaneapi::ObjectRef* _internal_mutable_graph();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor.setContentGraphRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_setContentGraphRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor_setContentGraphRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* objectptr_;
    ::octaneapi::ObjectRef* graph_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class ApiNodeGraphEditor_destroyRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor.destroyRequest) */ {
 public:
  inline ApiNodeGraphEditor_destroyRequest() : ApiNodeGraphEditor_destroyRequest(nullptr) {}
  ~ApiNodeGraphEditor_destroyRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor_destroyRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor_destroyRequest(const ApiNodeGraphEditor_destroyRequest& from) : ApiNodeGraphEditor_destroyRequest(nullptr, from) {}
  inline ApiNodeGraphEditor_destroyRequest(ApiNodeGraphEditor_destroyRequest&& from) noexcept
      : ApiNodeGraphEditor_destroyRequest(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor_destroyRequest& operator=(const ApiNodeGraphEditor_destroyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor_destroyRequest& operator=(ApiNodeGraphEditor_destroyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor_destroyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor_destroyRequest* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor_destroyRequest*>(
        &_ApiNodeGraphEditor_destroyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ApiNodeGraphEditor_destroyRequest& a, ApiNodeGraphEditor_destroyRequest& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor_destroyRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor_destroyRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor_destroyRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiNodeGraphEditor_destroyRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiNodeGraphEditor_destroyRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor.destroyRequest"; }

 protected:
  explicit ApiNodeGraphEditor_destroyRequest(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor_destroyRequest(::google::protobuf::Arena* arena, const ApiNodeGraphEditor_destroyRequest& from);
  ApiNodeGraphEditor_destroyRequest(::google::protobuf::Arena* arena, ApiNodeGraphEditor_destroyRequest&& from) noexcept
      : ApiNodeGraphEditor_destroyRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectPtrFieldNumber = 1,
  };
  // .octaneapi.ObjectRef objectPtr = 1;
  bool has_objectptr() const;
  void clear_objectptr() ;
  const ::octaneapi::ObjectRef& objectptr() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_objectptr();
  ::octaneapi::ObjectRef* mutable_objectptr();
  void set_allocated_objectptr(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_objectptr();

  private:
  const ::octaneapi::ObjectRef& _internal_objectptr() const;
  ::octaneapi::ObjectRef* _internal_mutable_objectptr();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor.destroyRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_destroyRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor_destroyRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* objectptr_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class ApiNodeGraphEditor_createResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor.createResponse) */ {
 public:
  inline ApiNodeGraphEditor_createResponse() : ApiNodeGraphEditor_createResponse(nullptr) {}
  ~ApiNodeGraphEditor_createResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor_createResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor_createResponse(const ApiNodeGraphEditor_createResponse& from) : ApiNodeGraphEditor_createResponse(nullptr, from) {}
  inline ApiNodeGraphEditor_createResponse(ApiNodeGraphEditor_createResponse&& from) noexcept
      : ApiNodeGraphEditor_createResponse(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor_createResponse& operator=(const ApiNodeGraphEditor_createResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor_createResponse& operator=(ApiNodeGraphEditor_createResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor_createResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor_createResponse* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor_createResponse*>(
        &_ApiNodeGraphEditor_createResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ApiNodeGraphEditor_createResponse& a, ApiNodeGraphEditor_createResponse& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor_createResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor_createResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor_createResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiNodeGraphEditor_createResponse>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiNodeGraphEditor_createResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor.createResponse"; }

 protected:
  explicit ApiNodeGraphEditor_createResponse(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor_createResponse(::google::protobuf::Arena* arena, const ApiNodeGraphEditor_createResponse& from);
  ApiNodeGraphEditor_createResponse(::google::protobuf::Arena* arena, ApiNodeGraphEditor_createResponse&& from) noexcept
      : ApiNodeGraphEditor_createResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // .octaneapi.ObjectRef result = 1;
  bool has_result() const;
  void clear_result() ;
  const ::octaneapi::ObjectRef& result() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_result();
  ::octaneapi::ObjectRef* mutable_result();
  void set_allocated_result(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_result(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_result();

  private:
  const ::octaneapi::ObjectRef& _internal_result() const;
  ::octaneapi::ObjectRef* _internal_mutable_result();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor.createResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_createResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor_createResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class ApiNodeGraphEditor_createRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor.createRequest) */ {
 public:
  inline ApiNodeGraphEditor_createRequest() : ApiNodeGraphEditor_createRequest(nullptr) {}
  ~ApiNodeGraphEditor_createRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor_createRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor_createRequest(const ApiNodeGraphEditor_createRequest& from) : ApiNodeGraphEditor_createRequest(nullptr, from) {}
  inline ApiNodeGraphEditor_createRequest(ApiNodeGraphEditor_createRequest&& from) noexcept
      : ApiNodeGraphEditor_createRequest(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor_createRequest& operator=(const ApiNodeGraphEditor_createRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor_createRequest& operator=(ApiNodeGraphEditor_createRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor_createRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor_createRequest* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor_createRequest*>(
        &_ApiNodeGraphEditor_createRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ApiNodeGraphEditor_createRequest& a, ApiNodeGraphEditor_createRequest& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor_createRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor_createRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor_createRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiNodeGraphEditor_createRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiNodeGraphEditor_createRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor.createRequest"; }

 protected:
  explicit ApiNodeGraphEditor_createRequest(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor_createRequest(::google::protobuf::Arena* arena, const ApiNodeGraphEditor_createRequest& from);
  ApiNodeGraphEditor_createRequest(::google::protobuf::Arena* arena, ApiNodeGraphEditor_createRequest&& from) noexcept
      : ApiNodeGraphEditor_createRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContentFieldNumber = 1,
    kPrivateDataFieldNumber = 3,
    kUnfoldFieldNumber = 2,
  };
  // .octaneapi.ObjectRef content = 1;
  bool has_content() const;
  void clear_content() ;
  const ::octaneapi::ObjectRef& content() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_content();
  ::octaneapi::ObjectRef* mutable_content();
  void set_allocated_content(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_content(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_content();

  private:
  const ::octaneapi::ObjectRef& _internal_content() const;
  ::octaneapi::ObjectRef* _internal_mutable_content();

  public:
  // uint64 privateData = 3;
  void clear_privatedata() ;
  ::uint64_t privatedata() const;
  void set_privatedata(::uint64_t value);

  private:
  ::uint64_t _internal_privatedata() const;
  void _internal_set_privatedata(::uint64_t value);

  public:
  // bool unfold = 2;
  void clear_unfold() ;
  bool unfold() const;
  void set_unfold(bool value);

  private:
  bool _internal_unfold() const;
  void _internal_set_unfold(bool value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor.createRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_createRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor_createRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* content_;
    ::uint64_t privatedata_;
    bool unfold_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};
// -------------------------------------------------------------------

class ApiNodeGraphEditor_addGraphRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiNodeGraphEditor.addGraphRequest) */ {
 public:
  inline ApiNodeGraphEditor_addGraphRequest() : ApiNodeGraphEditor_addGraphRequest(nullptr) {}
  ~ApiNodeGraphEditor_addGraphRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiNodeGraphEditor_addGraphRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiNodeGraphEditor_addGraphRequest(const ApiNodeGraphEditor_addGraphRequest& from) : ApiNodeGraphEditor_addGraphRequest(nullptr, from) {}
  inline ApiNodeGraphEditor_addGraphRequest(ApiNodeGraphEditor_addGraphRequest&& from) noexcept
      : ApiNodeGraphEditor_addGraphRequest(nullptr, std::move(from)) {}
  inline ApiNodeGraphEditor_addGraphRequest& operator=(const ApiNodeGraphEditor_addGraphRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiNodeGraphEditor_addGraphRequest& operator=(ApiNodeGraphEditor_addGraphRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiNodeGraphEditor_addGraphRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiNodeGraphEditor_addGraphRequest* internal_default_instance() {
    return reinterpret_cast<const ApiNodeGraphEditor_addGraphRequest*>(
        &_ApiNodeGraphEditor_addGraphRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(ApiNodeGraphEditor_addGraphRequest& a, ApiNodeGraphEditor_addGraphRequest& b) { a.Swap(&b); }
  inline void Swap(ApiNodeGraphEditor_addGraphRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiNodeGraphEditor_addGraphRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiNodeGraphEditor_addGraphRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiNodeGraphEditor_addGraphRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiNodeGraphEditor_addGraphRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiNodeGraphEditor.addGraphRequest"; }

 protected:
  explicit ApiNodeGraphEditor_addGraphRequest(::google::protobuf::Arena* arena);
  ApiNodeGraphEditor_addGraphRequest(::google::protobuf::Arena* arena, const ApiNodeGraphEditor_addGraphRequest& from);
  ApiNodeGraphEditor_addGraphRequest(::google::protobuf::Arena* arena, ApiNodeGraphEditor_addGraphRequest&& from) noexcept
      : ApiNodeGraphEditor_addGraphRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectPtrFieldNumber = 1,
    kGraphFieldNumber = 2,
  };
  // .octaneapi.ObjectRef objectPtr = 1;
  bool has_objectptr() const;
  void clear_objectptr() ;
  const ::octaneapi::ObjectRef& objectptr() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_objectptr();
  ::octaneapi::ObjectRef* mutable_objectptr();
  void set_allocated_objectptr(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_objectptr();

  private:
  const ::octaneapi::ObjectRef& _internal_objectptr() const;
  ::octaneapi::ObjectRef* _internal_mutable_objectptr();

  public:
  // .octaneapi.ObjectRef graph = 2;
  bool has_graph() const;
  void clear_graph() ;
  const ::octaneapi::ObjectRef& graph() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_graph();
  ::octaneapi::ObjectRef* mutable_graph();
  void set_allocated_graph(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_graph(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_graph();

  private:
  const ::octaneapi::ObjectRef& _internal_graph() const;
  ::octaneapi::ObjectRef* _internal_mutable_graph();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiNodeGraphEditor.addGraphRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiNodeGraphEditor_addGraphRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiNodeGraphEditor_addGraphRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* objectptr_;
    ::octaneapi::ObjectRef* graph_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apinodegrapheditor_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NodeGraphEditorArrayT

// repeated .octaneapi.ApiNodeGraphEditor data = 1;
inline int NodeGraphEditorArrayT::_internal_data_size() const {
  return _internal_data().size();
}
inline int NodeGraphEditorArrayT::data_size() const {
  return _internal_data_size();
}
inline void NodeGraphEditorArrayT::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Clear();
}
inline ::octaneapi::ApiNodeGraphEditor* NodeGraphEditorArrayT::mutable_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:octaneapi.NodeGraphEditorArrayT.data)
  return _internal_mutable_data()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>* NodeGraphEditorArrayT::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:octaneapi.NodeGraphEditorArrayT.data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_data();
}
inline const ::octaneapi::ApiNodeGraphEditor& NodeGraphEditorArrayT::data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.NodeGraphEditorArrayT.data)
  return _internal_data().Get(index);
}
inline ::octaneapi::ApiNodeGraphEditor* NodeGraphEditorArrayT::add_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::octaneapi::ApiNodeGraphEditor* _add = _internal_mutable_data()->Add();
  // @@protoc_insertion_point(field_add:octaneapi.NodeGraphEditorArrayT.data)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>& NodeGraphEditorArrayT::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:octaneapi.NodeGraphEditorArrayT.data)
  return _internal_data();
}
inline const ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>&
NodeGraphEditorArrayT::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedPtrField<::octaneapi::ApiNodeGraphEditor>*
NodeGraphEditorArrayT::_internal_mutable_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.data_;
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor_createRequest

// .octaneapi.ObjectRef content = 1;
inline bool ApiNodeGraphEditor_createRequest::has_content() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.content_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_createRequest::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.content_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_createRequest::content() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.createRequest.content)
  return _internal_content();
}
inline void ApiNodeGraphEditor_createRequest::unsafe_arena_set_allocated_content(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }
  _impl_.content_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.createRequest.content)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createRequest::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.content_;
  _impl_.content_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createRequest::unsafe_arena_release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.createRequest.content)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.content_;
  _impl_.content_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createRequest::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.content_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.content_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createRequest::mutable_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.createRequest.content)
  return _msg;
}
inline void ApiNodeGraphEditor_createRequest::set_allocated_content(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.content_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.createRequest.content)
}

// bool unfold = 2;
inline void ApiNodeGraphEditor_createRequest::clear_unfold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unfold_ = false;
}
inline bool ApiNodeGraphEditor_createRequest::unfold() const {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.createRequest.unfold)
  return _internal_unfold();
}
inline void ApiNodeGraphEditor_createRequest::set_unfold(bool value) {
  _internal_set_unfold(value);
  // @@protoc_insertion_point(field_set:octaneapi.ApiNodeGraphEditor.createRequest.unfold)
}
inline bool ApiNodeGraphEditor_createRequest::_internal_unfold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unfold_;
}
inline void ApiNodeGraphEditor_createRequest::_internal_set_unfold(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unfold_ = value;
}

// uint64 privateData = 3;
inline void ApiNodeGraphEditor_createRequest::clear_privatedata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.privatedata_ = ::uint64_t{0u};
}
inline ::uint64_t ApiNodeGraphEditor_createRequest::privatedata() const {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.createRequest.privateData)
  return _internal_privatedata();
}
inline void ApiNodeGraphEditor_createRequest::set_privatedata(::uint64_t value) {
  _internal_set_privatedata(value);
  // @@protoc_insertion_point(field_set:octaneapi.ApiNodeGraphEditor.createRequest.privateData)
}
inline ::uint64_t ApiNodeGraphEditor_createRequest::_internal_privatedata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.privatedata_;
}
inline void ApiNodeGraphEditor_createRequest::_internal_set_privatedata(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.privatedata_ = value;
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor_createResponse

// .octaneapi.ObjectRef result = 1;
inline bool ApiNodeGraphEditor_createResponse::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.result_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_createResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_createResponse::result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.createResponse.result)
  return _internal_result();
}
inline void ApiNodeGraphEditor_createResponse::unsafe_arena_set_allocated_result(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.createResponse.result)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createResponse::release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.result_;
  _impl_.result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createResponse::unsafe_arena_release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.createResponse.result)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createResponse::_internal_mutable_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.result_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_createResponse::mutable_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.createResponse.result)
  return _msg;
}
inline void ApiNodeGraphEditor_createResponse::set_allocated_result(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.createResponse.result)
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor_destroyRequest

// .octaneapi.ObjectRef objectPtr = 1;
inline bool ApiNodeGraphEditor_destroyRequest::has_objectptr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.objectptr_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_destroyRequest::_internal_objectptr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.objectptr_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_destroyRequest::objectptr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.destroyRequest.objectPtr)
  return _internal_objectptr();
}
inline void ApiNodeGraphEditor_destroyRequest::unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }
  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.destroyRequest.objectPtr)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_destroyRequest::release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_destroyRequest::unsafe_arena_release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.destroyRequest.objectPtr)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_destroyRequest::_internal_mutable_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.objectptr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.objectptr_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_destroyRequest::mutable_objectptr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_objectptr();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.destroyRequest.objectPtr)
  return _msg;
}
inline void ApiNodeGraphEditor_destroyRequest::set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.destroyRequest.objectPtr)
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor_setContentGraphRequest

// .octaneapi.ObjectRef objectPtr = 1;
inline bool ApiNodeGraphEditor_setContentGraphRequest::has_objectptr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.objectptr_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_setContentGraphRequest::_internal_objectptr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.objectptr_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_setContentGraphRequest::objectptr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.objectPtr)
  return _internal_objectptr();
}
inline void ApiNodeGraphEditor_setContentGraphRequest::unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }
  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.objectPtr)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::unsafe_arena_release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.objectPtr)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::_internal_mutable_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.objectptr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.objectptr_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::mutable_objectptr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_objectptr();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.objectPtr)
  return _msg;
}
inline void ApiNodeGraphEditor_setContentGraphRequest::set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.objectPtr)
}

// .octaneapi.ObjectRef graph = 2;
inline bool ApiNodeGraphEditor_setContentGraphRequest::has_graph() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.graph_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_setContentGraphRequest::_internal_graph() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.graph_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_setContentGraphRequest::graph() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.graph)
  return _internal_graph();
}
inline void ApiNodeGraphEditor_setContentGraphRequest::unsafe_arena_set_allocated_graph(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_);
  }
  _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.graph)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::release_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::octaneapi::ObjectRef* released = _impl_.graph_;
  _impl_.graph_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::unsafe_arena_release_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.graph)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::octaneapi::ObjectRef* temp = _impl_.graph_;
  _impl_.graph_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::_internal_mutable_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.graph_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.graph_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_setContentGraphRequest::mutable_graph() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_graph();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.graph)
  return _msg;
}
inline void ApiNodeGraphEditor_setContentGraphRequest::set_allocated_graph(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.setContentGraphRequest.graph)
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor_addGraphRequest

// .octaneapi.ObjectRef objectPtr = 1;
inline bool ApiNodeGraphEditor_addGraphRequest::has_objectptr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.objectptr_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_addGraphRequest::_internal_objectptr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.objectptr_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_addGraphRequest::objectptr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.addGraphRequest.objectPtr)
  return _internal_objectptr();
}
inline void ApiNodeGraphEditor_addGraphRequest::unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }
  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.addGraphRequest.objectPtr)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::unsafe_arena_release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.addGraphRequest.objectPtr)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::_internal_mutable_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.objectptr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.objectptr_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::mutable_objectptr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_objectptr();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.addGraphRequest.objectPtr)
  return _msg;
}
inline void ApiNodeGraphEditor_addGraphRequest::set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.addGraphRequest.objectPtr)
}

// .octaneapi.ObjectRef graph = 2;
inline bool ApiNodeGraphEditor_addGraphRequest::has_graph() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.graph_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_addGraphRequest::_internal_graph() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.graph_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiNodeGraphEditor_addGraphRequest::graph() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiNodeGraphEditor.addGraphRequest.graph)
  return _internal_graph();
}
inline void ApiNodeGraphEditor_addGraphRequest::unsafe_arena_set_allocated_graph(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_);
  }
  _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiNodeGraphEditor.addGraphRequest.graph)
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::release_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::octaneapi::ObjectRef* released = _impl_.graph_;
  _impl_.graph_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::unsafe_arena_release_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiNodeGraphEditor.addGraphRequest.graph)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::octaneapi::ObjectRef* temp = _impl_.graph_;
  _impl_.graph_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::_internal_mutable_graph() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.graph_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.graph_;
}
inline ::octaneapi::ObjectRef* ApiNodeGraphEditor_addGraphRequest::mutable_graph() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_graph();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiNodeGraphEditor.addGraphRequest.graph)
  return _msg;
}
inline void ApiNodeGraphEditor_addGraphRequest::set_allocated_graph(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.graph_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.graph_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiNodeGraphEditor.addGraphRequest.graph)
}

// -------------------------------------------------------------------

// ApiNodeGraphEditor

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace octaneapi


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_apinodegrapheditor_2eproto_2epb_2eh
