// Copyright (C) 2025 OTOY NZ Ltd.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: apititlecomponent.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_apititlecomponent_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_apititlecomponent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
#include "google/protobuf/empty.pb.h"
#include "apiguicomponent.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_apititlecomponent_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_apititlecomponent_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_apititlecomponent_2eproto;
namespace octaneapi {
class ApiTitleComponent;
struct ApiTitleComponentDefaultTypeInternal;
extern ApiTitleComponentDefaultTypeInternal _ApiTitleComponent_default_instance_;
class ApiTitleComponent_createRequest;
struct ApiTitleComponent_createRequestDefaultTypeInternal;
extern ApiTitleComponent_createRequestDefaultTypeInternal _ApiTitleComponent_createRequest_default_instance_;
class ApiTitleComponent_createResponse;
struct ApiTitleComponent_createResponseDefaultTypeInternal;
extern ApiTitleComponent_createResponseDefaultTypeInternal _ApiTitleComponent_createResponse_default_instance_;
class ApiTitleComponent_destroyRequest;
struct ApiTitleComponent_destroyRequestDefaultTypeInternal;
extern ApiTitleComponent_destroyRequestDefaultTypeInternal _ApiTitleComponent_destroyRequest_default_instance_;
}  // namespace octaneapi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace octaneapi {

// ===================================================================


// -------------------------------------------------------------------

class ApiTitleComponent_createRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiTitleComponent.createRequest) */ {
 public:
  inline ApiTitleComponent_createRequest() : ApiTitleComponent_createRequest(nullptr) {}
  ~ApiTitleComponent_createRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiTitleComponent_createRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiTitleComponent_createRequest(const ApiTitleComponent_createRequest& from) : ApiTitleComponent_createRequest(nullptr, from) {}
  inline ApiTitleComponent_createRequest(ApiTitleComponent_createRequest&& from) noexcept
      : ApiTitleComponent_createRequest(nullptr, std::move(from)) {}
  inline ApiTitleComponent_createRequest& operator=(const ApiTitleComponent_createRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiTitleComponent_createRequest& operator=(ApiTitleComponent_createRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiTitleComponent_createRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiTitleComponent_createRequest* internal_default_instance() {
    return reinterpret_cast<const ApiTitleComponent_createRequest*>(
        &_ApiTitleComponent_createRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ApiTitleComponent_createRequest& a, ApiTitleComponent_createRequest& b) { a.Swap(&b); }
  inline void Swap(ApiTitleComponent_createRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiTitleComponent_createRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiTitleComponent_createRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiTitleComponent_createRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiTitleComponent_createRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiTitleComponent.createRequest"; }

 protected:
  explicit ApiTitleComponent_createRequest(::google::protobuf::Arena* arena);
  ApiTitleComponent_createRequest(::google::protobuf::Arena* arena, const ApiTitleComponent_createRequest& from);
  ApiTitleComponent_createRequest(::google::protobuf::Arena* arena, ApiTitleComponent_createRequest&& from) noexcept
      : ApiTitleComponent_createRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* value);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiTitleComponent.createRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      54, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiTitleComponent_createRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiTitleComponent_createRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr text_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apititlecomponent_2eproto;
};
// -------------------------------------------------------------------

class ApiTitleComponent final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:octaneapi.ApiTitleComponent) */ {
 public:
  inline ApiTitleComponent() : ApiTitleComponent(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiTitleComponent(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiTitleComponent(const ApiTitleComponent& from) : ApiTitleComponent(nullptr, from) {}
  inline ApiTitleComponent(ApiTitleComponent&& from) noexcept
      : ApiTitleComponent(nullptr, std::move(from)) {}
  inline ApiTitleComponent& operator=(const ApiTitleComponent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiTitleComponent& operator=(ApiTitleComponent&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiTitleComponent& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiTitleComponent* internal_default_instance() {
    return reinterpret_cast<const ApiTitleComponent*>(
        &_ApiTitleComponent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ApiTitleComponent& a, ApiTitleComponent& b) { a.Swap(&b); }
  inline void Swap(ApiTitleComponent* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiTitleComponent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiTitleComponent* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ApiTitleComponent>(arena);
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiTitleComponent"; }

 protected:
  explicit ApiTitleComponent(::google::protobuf::Arena* arena);
  ApiTitleComponent(::google::protobuf::Arena* arena, const ApiTitleComponent& from);
  ApiTitleComponent(::google::protobuf::Arena* arena, ApiTitleComponent&& from) noexcept
      : ApiTitleComponent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using createRequest = ApiTitleComponent_createRequest;
  using createResponse = ApiTitleComponent_createResponse;
  using destroyRequest = ApiTitleComponent_destroyRequest;

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:octaneapi.ApiTitleComponent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiTitleComponent_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiTitleComponent& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_apititlecomponent_2eproto;
};
// -------------------------------------------------------------------

class ApiTitleComponent_destroyRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiTitleComponent.destroyRequest) */ {
 public:
  inline ApiTitleComponent_destroyRequest() : ApiTitleComponent_destroyRequest(nullptr) {}
  ~ApiTitleComponent_destroyRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiTitleComponent_destroyRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiTitleComponent_destroyRequest(const ApiTitleComponent_destroyRequest& from) : ApiTitleComponent_destroyRequest(nullptr, from) {}
  inline ApiTitleComponent_destroyRequest(ApiTitleComponent_destroyRequest&& from) noexcept
      : ApiTitleComponent_destroyRequest(nullptr, std::move(from)) {}
  inline ApiTitleComponent_destroyRequest& operator=(const ApiTitleComponent_destroyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiTitleComponent_destroyRequest& operator=(ApiTitleComponent_destroyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiTitleComponent_destroyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiTitleComponent_destroyRequest* internal_default_instance() {
    return reinterpret_cast<const ApiTitleComponent_destroyRequest*>(
        &_ApiTitleComponent_destroyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ApiTitleComponent_destroyRequest& a, ApiTitleComponent_destroyRequest& b) { a.Swap(&b); }
  inline void Swap(ApiTitleComponent_destroyRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiTitleComponent_destroyRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiTitleComponent_destroyRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiTitleComponent_destroyRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiTitleComponent_destroyRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiTitleComponent.destroyRequest"; }

 protected:
  explicit ApiTitleComponent_destroyRequest(::google::protobuf::Arena* arena);
  ApiTitleComponent_destroyRequest(::google::protobuf::Arena* arena, const ApiTitleComponent_destroyRequest& from);
  ApiTitleComponent_destroyRequest(::google::protobuf::Arena* arena, ApiTitleComponent_destroyRequest&& from) noexcept
      : ApiTitleComponent_destroyRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectPtrFieldNumber = 1,
  };
  // .octaneapi.ObjectRef objectPtr = 1;
  bool has_objectptr() const;
  void clear_objectptr() ;
  const ::octaneapi::ObjectRef& objectptr() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_objectptr();
  ::octaneapi::ObjectRef* mutable_objectptr();
  void set_allocated_objectptr(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_objectptr();

  private:
  const ::octaneapi::ObjectRef& _internal_objectptr() const;
  ::octaneapi::ObjectRef* _internal_mutable_objectptr();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiTitleComponent.destroyRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiTitleComponent_destroyRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiTitleComponent_destroyRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* objectptr_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apititlecomponent_2eproto;
};
// -------------------------------------------------------------------

class ApiTitleComponent_createResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.ApiTitleComponent.createResponse) */ {
 public:
  inline ApiTitleComponent_createResponse() : ApiTitleComponent_createResponse(nullptr) {}
  ~ApiTitleComponent_createResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ApiTitleComponent_createResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ApiTitleComponent_createResponse(const ApiTitleComponent_createResponse& from) : ApiTitleComponent_createResponse(nullptr, from) {}
  inline ApiTitleComponent_createResponse(ApiTitleComponent_createResponse&& from) noexcept
      : ApiTitleComponent_createResponse(nullptr, std::move(from)) {}
  inline ApiTitleComponent_createResponse& operator=(const ApiTitleComponent_createResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApiTitleComponent_createResponse& operator=(ApiTitleComponent_createResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApiTitleComponent_createResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApiTitleComponent_createResponse* internal_default_instance() {
    return reinterpret_cast<const ApiTitleComponent_createResponse*>(
        &_ApiTitleComponent_createResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ApiTitleComponent_createResponse& a, ApiTitleComponent_createResponse& b) { a.Swap(&b); }
  inline void Swap(ApiTitleComponent_createResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApiTitleComponent_createResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApiTitleComponent_createResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ApiTitleComponent_createResponse>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ApiTitleComponent_createResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "octaneapi.ApiTitleComponent.createResponse"; }

 protected:
  explicit ApiTitleComponent_createResponse(::google::protobuf::Arena* arena);
  ApiTitleComponent_createResponse(::google::protobuf::Arena* arena, const ApiTitleComponent_createResponse& from);
  ApiTitleComponent_createResponse(::google::protobuf::Arena* arena, ApiTitleComponent_createResponse&& from) noexcept
      : ApiTitleComponent_createResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // .octaneapi.ObjectRef result = 1;
  bool has_result() const;
  void clear_result() ;
  const ::octaneapi::ObjectRef& result() const;
  PROTOBUF_NODISCARD ::octaneapi::ObjectRef* release_result();
  ::octaneapi::ObjectRef* mutable_result();
  void set_allocated_result(::octaneapi::ObjectRef* value);
  void unsafe_arena_set_allocated_result(::octaneapi::ObjectRef* value);
  ::octaneapi::ObjectRef* unsafe_arena_release_result();

  private:
  const ::octaneapi::ObjectRef& _internal_result() const;
  ::octaneapi::ObjectRef* _internal_mutable_result();

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.ApiTitleComponent.createResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ApiTitleComponent_createResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ApiTitleComponent_createResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::octaneapi::ObjectRef* result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_apititlecomponent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ApiTitleComponent_createRequest

// string text = 1;
inline void ApiTitleComponent_createRequest::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
}
inline const std::string& ApiTitleComponent_createRequest::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiTitleComponent.createRequest.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ApiTitleComponent_createRequest::set_text(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:octaneapi.ApiTitleComponent.createRequest.text)
}
inline std::string* ApiTitleComponent_createRequest::mutable_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiTitleComponent.createRequest.text)
  return _s;
}
inline const std::string& ApiTitleComponent_createRequest::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void ApiTitleComponent_createRequest::_internal_set_text(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline std::string* ApiTitleComponent_createRequest::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline std::string* ApiTitleComponent_createRequest::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiTitleComponent.createRequest.text)
  return _impl_.text_.Release();
}
inline void ApiTitleComponent_createRequest::set_allocated_text(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_.IsDefault()) {
          _impl_.text_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiTitleComponent.createRequest.text)
}

// -------------------------------------------------------------------

// ApiTitleComponent_createResponse

// .octaneapi.ObjectRef result = 1;
inline bool ApiTitleComponent_createResponse::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.result_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiTitleComponent_createResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.result_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiTitleComponent_createResponse::result() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiTitleComponent.createResponse.result)
  return _internal_result();
}
inline void ApiTitleComponent_createResponse::unsafe_arena_set_allocated_result(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }
  _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiTitleComponent.createResponse.result)
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_createResponse::release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.result_;
  _impl_.result_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_createResponse::unsafe_arena_release_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiTitleComponent.createResponse.result)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.result_;
  _impl_.result_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_createResponse::_internal_mutable_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.result_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.result_;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_createResponse::mutable_result() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiTitleComponent.createResponse.result)
  return _msg;
}
inline void ApiTitleComponent_createResponse::set_allocated_result(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.result_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.result_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiTitleComponent.createResponse.result)
}

// -------------------------------------------------------------------

// ApiTitleComponent_destroyRequest

// .octaneapi.ObjectRef objectPtr = 1;
inline bool ApiTitleComponent_destroyRequest::has_objectptr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.objectptr_ != nullptr);
  return value;
}
inline const ::octaneapi::ObjectRef& ApiTitleComponent_destroyRequest::_internal_objectptr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::octaneapi::ObjectRef* p = _impl_.objectptr_;
  return p != nullptr ? *p : reinterpret_cast<const ::octaneapi::ObjectRef&>(::octaneapi::_ObjectRef_default_instance_);
}
inline const ::octaneapi::ObjectRef& ApiTitleComponent_destroyRequest::objectptr() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.ApiTitleComponent.destroyRequest.objectPtr)
  return _internal_objectptr();
}
inline void ApiTitleComponent_destroyRequest::unsafe_arena_set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }
  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.ApiTitleComponent.destroyRequest.objectPtr)
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_destroyRequest::release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* released = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_destroyRequest::unsafe_arena_release_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:octaneapi.ApiTitleComponent.destroyRequest.objectPtr)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::octaneapi::ObjectRef* temp = _impl_.objectptr_;
  _impl_.objectptr_ = nullptr;
  return temp;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_destroyRequest::_internal_mutable_objectptr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.objectptr_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::octaneapi::ObjectRef>(GetArena());
    _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(p);
  }
  return _impl_.objectptr_;
}
inline ::octaneapi::ObjectRef* ApiTitleComponent_destroyRequest::mutable_objectptr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::octaneapi::ObjectRef* _msg = _internal_mutable_objectptr();
  // @@protoc_insertion_point(field_mutable:octaneapi.ApiTitleComponent.destroyRequest.objectPtr)
  return _msg;
}
inline void ApiTitleComponent_destroyRequest::set_allocated_objectptr(::octaneapi::ObjectRef* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.objectptr_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.objectptr_ = reinterpret_cast<::octaneapi::ObjectRef*>(value);
  // @@protoc_insertion_point(field_set_allocated:octaneapi.ApiTitleComponent.destroyRequest.objectPtr)
}

// -------------------------------------------------------------------

// ApiTitleComponent

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace octaneapi


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_apititlecomponent_2eproto_2epb_2eh
