// Copyright (C) 2026 OTOY NZ Ltd.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: callbackstream.proto
// Protobuf C++ Version: 6.31.1

#ifndef callbackstream_2eproto_2epb_2eh
#define callbackstream_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_callbackstream_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_callbackstream_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_callbackstream_2eproto;
}  // extern "C"
namespace octaneapi {
class OnNewImageData;
struct OnNewImageDataDefaultTypeInternal;
extern OnNewImageDataDefaultTypeInternal _OnNewImageData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OnNewImageData_class_data_;
class OnNewRenderedImageRequest;
struct OnNewRenderedImageRequestDefaultTypeInternal;
extern OnNewRenderedImageRequestDefaultTypeInternal _OnNewRenderedImageRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OnNewRenderedImageRequest_class_data_;
class OnProjectManagerData;
struct OnProjectManagerDataDefaultTypeInternal;
extern OnProjectManagerDataDefaultTypeInternal _OnProjectManagerData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OnProjectManagerData_class_data_;
class OnRenderFailureData;
struct OnRenderFailureDataDefaultTypeInternal;
extern OnRenderFailureDataDefaultTypeInternal _OnRenderFailureData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OnRenderFailureData_class_data_;
class OnStatisticsData;
struct OnStatisticsDataDefaultTypeInternal;
extern OnStatisticsDataDefaultTypeInternal _OnStatisticsData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OnStatisticsData_class_data_;
class StreamCallbackRequest;
struct StreamCallbackRequestDefaultTypeInternal;
extern StreamCallbackRequestDefaultTypeInternal _StreamCallbackRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StreamCallbackRequest_class_data_;
}  // namespace octaneapi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace octaneapi {

// ===================================================================


// -------------------------------------------------------------------

class OnStatisticsData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.OnStatisticsData) */ {
 public:
  inline OnStatisticsData() : OnStatisticsData(nullptr) {}
  ~OnStatisticsData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OnStatisticsData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OnStatisticsData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OnStatisticsData(::google::protobuf::internal::ConstantInitialized);

  inline OnStatisticsData(const OnStatisticsData& from) : OnStatisticsData(nullptr, from) {}
  inline OnStatisticsData(OnStatisticsData&& from) noexcept
      : OnStatisticsData(nullptr, ::std::move(from)) {}
  inline OnStatisticsData& operator=(const OnStatisticsData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnStatisticsData& operator=(OnStatisticsData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnStatisticsData& default_instance() {
    return *reinterpret_cast<const OnStatisticsData*>(
        &_OnStatisticsData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(OnStatisticsData& a, OnStatisticsData& b) { a.Swap(&b); }
  inline void Swap(OnStatisticsData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnStatisticsData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnStatisticsData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OnStatisticsData>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OnStatisticsData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.OnStatisticsData"; }

 protected:
  explicit OnStatisticsData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OnStatisticsData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OnStatisticsData& from);
  OnStatisticsData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OnStatisticsData&& from) noexcept
      : OnStatisticsData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserDataFieldNumber = 1,
  };
  // uint64 user_data = 1;
  void clear_user_data() ;
  ::uint64_t user_data() const;
  void set_user_data(::uint64_t value);

  private:
  ::uint64_t _internal_user_data() const;
  void _internal_set_user_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.OnStatisticsData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OnStatisticsData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OnStatisticsData_class_data_;
// -------------------------------------------------------------------

class OnRenderFailureData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.OnRenderFailureData) */ {
 public:
  inline OnRenderFailureData() : OnRenderFailureData(nullptr) {}
  ~OnRenderFailureData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OnRenderFailureData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OnRenderFailureData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OnRenderFailureData(::google::protobuf::internal::ConstantInitialized);

  inline OnRenderFailureData(const OnRenderFailureData& from) : OnRenderFailureData(nullptr, from) {}
  inline OnRenderFailureData(OnRenderFailureData&& from) noexcept
      : OnRenderFailureData(nullptr, ::std::move(from)) {}
  inline OnRenderFailureData& operator=(const OnRenderFailureData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnRenderFailureData& operator=(OnRenderFailureData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnRenderFailureData& default_instance() {
    return *reinterpret_cast<const OnRenderFailureData*>(
        &_OnRenderFailureData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OnRenderFailureData& a, OnRenderFailureData& b) { a.Swap(&b); }
  inline void Swap(OnRenderFailureData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnRenderFailureData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnRenderFailureData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OnRenderFailureData>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OnRenderFailureData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.OnRenderFailureData"; }

 protected:
  explicit OnRenderFailureData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OnRenderFailureData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OnRenderFailureData& from);
  OnRenderFailureData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OnRenderFailureData&& from) noexcept
      : OnRenderFailureData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserDataFieldNumber = 1,
  };
  // uint64 user_data = 1;
  void clear_user_data() ;
  ::uint64_t user_data() const;
  void set_user_data(::uint64_t value);

  private:
  ::uint64_t _internal_user_data() const;
  void _internal_set_user_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.OnRenderFailureData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OnRenderFailureData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OnRenderFailureData_class_data_;
// -------------------------------------------------------------------

class OnProjectManagerData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.OnProjectManagerData) */ {
 public:
  inline OnProjectManagerData() : OnProjectManagerData(nullptr) {}
  ~OnProjectManagerData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OnProjectManagerData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OnProjectManagerData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OnProjectManagerData(::google::protobuf::internal::ConstantInitialized);

  inline OnProjectManagerData(const OnProjectManagerData& from) : OnProjectManagerData(nullptr, from) {}
  inline OnProjectManagerData(OnProjectManagerData&& from) noexcept
      : OnProjectManagerData(nullptr, ::std::move(from)) {}
  inline OnProjectManagerData& operator=(const OnProjectManagerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnProjectManagerData& operator=(OnProjectManagerData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnProjectManagerData& default_instance() {
    return *reinterpret_cast<const OnProjectManagerData*>(
        &_OnProjectManagerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(OnProjectManagerData& a, OnProjectManagerData& b) { a.Swap(&b); }
  inline void Swap(OnProjectManagerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnProjectManagerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnProjectManagerData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OnProjectManagerData>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OnProjectManagerData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.OnProjectManagerData"; }

 protected:
  explicit OnProjectManagerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OnProjectManagerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OnProjectManagerData& from);
  OnProjectManagerData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OnProjectManagerData&& from) noexcept
      : OnProjectManagerData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserDataFieldNumber = 1,
  };
  // uint64 user_data = 1;
  void clear_user_data() ;
  ::uint64_t user_data() const;
  void set_user_data(::uint64_t value);

  private:
  ::uint64_t _internal_user_data() const;
  void _internal_set_user_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.OnProjectManagerData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OnProjectManagerData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OnProjectManagerData_class_data_;
// -------------------------------------------------------------------

class OnNewRenderedImageRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.OnNewRenderedImageRequest) */ {
 public:
  inline OnNewRenderedImageRequest() : OnNewRenderedImageRequest(nullptr) {}
  ~OnNewRenderedImageRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OnNewRenderedImageRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OnNewRenderedImageRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OnNewRenderedImageRequest(::google::protobuf::internal::ConstantInitialized);

  inline OnNewRenderedImageRequest(const OnNewRenderedImageRequest& from) : OnNewRenderedImageRequest(nullptr, from) {}
  inline OnNewRenderedImageRequest(OnNewRenderedImageRequest&& from) noexcept
      : OnNewRenderedImageRequest(nullptr, ::std::move(from)) {}
  inline OnNewRenderedImageRequest& operator=(const OnNewRenderedImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnNewRenderedImageRequest& operator=(OnNewRenderedImageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnNewRenderedImageRequest& default_instance() {
    return *reinterpret_cast<const OnNewRenderedImageRequest*>(
        &_OnNewRenderedImageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(OnNewRenderedImageRequest& a, OnNewRenderedImageRequest& b) { a.Swap(&b); }
  inline void Swap(OnNewRenderedImageRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnNewRenderedImageRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnNewRenderedImageRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OnNewRenderedImageRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OnNewRenderedImageRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.OnNewRenderedImageRequest"; }

 protected:
  explicit OnNewRenderedImageRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OnNewRenderedImageRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OnNewRenderedImageRequest& from);
  OnNewRenderedImageRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OnNewRenderedImageRequest&& from) noexcept
      : OnNewRenderedImageRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserDataFieldNumber = 1,
  };
  // uint64 user_data = 1;
  void clear_user_data() ;
  ::uint64_t user_data() const;
  void set_user_data(::uint64_t value);

  private:
  ::uint64_t _internal_user_data() const;
  void _internal_set_user_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.OnNewRenderedImageRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OnNewRenderedImageRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OnNewRenderedImageRequest_class_data_;
// -------------------------------------------------------------------

class OnNewImageData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.OnNewImageData) */ {
 public:
  inline OnNewImageData() : OnNewImageData(nullptr) {}
  ~OnNewImageData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OnNewImageData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OnNewImageData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OnNewImageData(::google::protobuf::internal::ConstantInitialized);

  inline OnNewImageData(const OnNewImageData& from) : OnNewImageData(nullptr, from) {}
  inline OnNewImageData(OnNewImageData&& from) noexcept
      : OnNewImageData(nullptr, ::std::move(from)) {}
  inline OnNewImageData& operator=(const OnNewImageData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OnNewImageData& operator=(OnNewImageData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OnNewImageData& default_instance() {
    return *reinterpret_cast<const OnNewImageData*>(
        &_OnNewImageData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OnNewImageData& a, OnNewImageData& b) { a.Swap(&b); }
  inline void Swap(OnNewImageData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OnNewImageData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OnNewImageData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OnNewImageData>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OnNewImageData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.OnNewImageData"; }

 protected:
  explicit OnNewImageData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OnNewImageData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OnNewImageData& from);
  OnNewImageData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OnNewImageData&& from) noexcept
      : OnNewImageData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserDataFieldNumber = 1,
  };
  // uint64 user_data = 1;
  void clear_user_data() ;
  ::uint64_t user_data() const;
  void set_user_data(::uint64_t value);

  private:
  ::uint64_t _internal_user_data() const;
  void _internal_set_user_data(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:octaneapi.OnNewImageData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OnNewImageData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OnNewImageData_class_data_;
// -------------------------------------------------------------------

class StreamCallbackRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:octaneapi.StreamCallbackRequest) */ {
 public:
  inline StreamCallbackRequest() : StreamCallbackRequest(nullptr) {}
  ~StreamCallbackRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StreamCallbackRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StreamCallbackRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StreamCallbackRequest(::google::protobuf::internal::ConstantInitialized);

  inline StreamCallbackRequest(const StreamCallbackRequest& from) : StreamCallbackRequest(nullptr, from) {}
  inline StreamCallbackRequest(StreamCallbackRequest&& from) noexcept
      : StreamCallbackRequest(nullptr, ::std::move(from)) {}
  inline StreamCallbackRequest& operator=(const StreamCallbackRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamCallbackRequest& operator=(StreamCallbackRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamCallbackRequest& default_instance() {
    return *reinterpret_cast<const StreamCallbackRequest*>(
        &_StreamCallbackRequest_default_instance_);
  }
  enum PayloadCase {
    kNewImage = 10,
    kRenderFailure = 11,
    kNewStatistics = 12,
    kProjectManagerChanged = 13,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(StreamCallbackRequest& a, StreamCallbackRequest& b) { a.Swap(&b); }
  inline void Swap(StreamCallbackRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamCallbackRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamCallbackRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StreamCallbackRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StreamCallbackRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "octaneapi.StreamCallbackRequest"; }

 protected:
  explicit StreamCallbackRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StreamCallbackRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StreamCallbackRequest& from);
  StreamCallbackRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StreamCallbackRequest&& from) noexcept
      : StreamCallbackRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewImageFieldNumber = 10,
    kRenderFailureFieldNumber = 11,
    kNewStatisticsFieldNumber = 12,
    kProjectManagerChangedFieldNumber = 13,
  };
  // .octaneapi.OnNewImageData newImage = 10;
  bool has_newimage() const;
  private:
  bool _internal_has_newimage() const;

  public:
  void clear_newimage() ;
  const ::octaneapi::OnNewImageData& newimage() const;
  [[nodiscard]] ::octaneapi::OnNewImageData* PROTOBUF_NULLABLE release_newimage();
  ::octaneapi::OnNewImageData* PROTOBUF_NONNULL mutable_newimage();
  void set_allocated_newimage(::octaneapi::OnNewImageData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_newimage(::octaneapi::OnNewImageData* PROTOBUF_NULLABLE value);
  ::octaneapi::OnNewImageData* PROTOBUF_NULLABLE unsafe_arena_release_newimage();

  private:
  const ::octaneapi::OnNewImageData& _internal_newimage() const;
  ::octaneapi::OnNewImageData* PROTOBUF_NONNULL _internal_mutable_newimage();

  public:
  // .octaneapi.OnRenderFailureData renderFailure = 11;
  bool has_renderfailure() const;
  private:
  bool _internal_has_renderfailure() const;

  public:
  void clear_renderfailure() ;
  const ::octaneapi::OnRenderFailureData& renderfailure() const;
  [[nodiscard]] ::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE release_renderfailure();
  ::octaneapi::OnRenderFailureData* PROTOBUF_NONNULL mutable_renderfailure();
  void set_allocated_renderfailure(::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_renderfailure(::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE value);
  ::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE unsafe_arena_release_renderfailure();

  private:
  const ::octaneapi::OnRenderFailureData& _internal_renderfailure() const;
  ::octaneapi::OnRenderFailureData* PROTOBUF_NONNULL _internal_mutable_renderfailure();

  public:
  // .octaneapi.OnStatisticsData newStatistics = 12;
  bool has_newstatistics() const;
  private:
  bool _internal_has_newstatistics() const;

  public:
  void clear_newstatistics() ;
  const ::octaneapi::OnStatisticsData& newstatistics() const;
  [[nodiscard]] ::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE release_newstatistics();
  ::octaneapi::OnStatisticsData* PROTOBUF_NONNULL mutable_newstatistics();
  void set_allocated_newstatistics(::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_newstatistics(::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE value);
  ::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE unsafe_arena_release_newstatistics();

  private:
  const ::octaneapi::OnStatisticsData& _internal_newstatistics() const;
  ::octaneapi::OnStatisticsData* PROTOBUF_NONNULL _internal_mutable_newstatistics();

  public:
  // .octaneapi.OnProjectManagerData projectManagerChanged = 13;
  bool has_projectmanagerchanged() const;
  private:
  bool _internal_has_projectmanagerchanged() const;

  public:
  void clear_projectmanagerchanged() ;
  const ::octaneapi::OnProjectManagerData& projectmanagerchanged() const;
  [[nodiscard]] ::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE release_projectmanagerchanged();
  ::octaneapi::OnProjectManagerData* PROTOBUF_NONNULL mutable_projectmanagerchanged();
  void set_allocated_projectmanagerchanged(::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_projectmanagerchanged(::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE value);
  ::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE unsafe_arena_release_projectmanagerchanged();

  private:
  const ::octaneapi::OnProjectManagerData& _internal_projectmanagerchanged() const;
  ::octaneapi::OnProjectManagerData* PROTOBUF_NONNULL _internal_mutable_projectmanagerchanged();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:octaneapi.StreamCallbackRequest)
 private:
  class _Internal;
  void set_has_newimage();
  void set_has_renderfailure();
  void set_has_newstatistics();
  void set_has_projectmanagerchanged();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StreamCallbackRequest& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE newimage_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE renderfailure_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE newstatistics_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE projectmanagerchanged_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_callbackstream_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StreamCallbackRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OnNewImageData

// uint64 user_data = 1;
inline void OnNewImageData::clear_user_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t OnNewImageData::user_data() const {
  // @@protoc_insertion_point(field_get:octaneapi.OnNewImageData.user_data)
  return _internal_user_data();
}
inline void OnNewImageData::set_user_data(::uint64_t value) {
  _internal_set_user_data(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:octaneapi.OnNewImageData.user_data)
}
inline ::uint64_t OnNewImageData::_internal_user_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_data_;
}
inline void OnNewImageData::_internal_set_user_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = value;
}

// -------------------------------------------------------------------

// OnRenderFailureData

// uint64 user_data = 1;
inline void OnRenderFailureData::clear_user_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t OnRenderFailureData::user_data() const {
  // @@protoc_insertion_point(field_get:octaneapi.OnRenderFailureData.user_data)
  return _internal_user_data();
}
inline void OnRenderFailureData::set_user_data(::uint64_t value) {
  _internal_set_user_data(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:octaneapi.OnRenderFailureData.user_data)
}
inline ::uint64_t OnRenderFailureData::_internal_user_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_data_;
}
inline void OnRenderFailureData::_internal_set_user_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = value;
}

// -------------------------------------------------------------------

// OnStatisticsData

// uint64 user_data = 1;
inline void OnStatisticsData::clear_user_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t OnStatisticsData::user_data() const {
  // @@protoc_insertion_point(field_get:octaneapi.OnStatisticsData.user_data)
  return _internal_user_data();
}
inline void OnStatisticsData::set_user_data(::uint64_t value) {
  _internal_set_user_data(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:octaneapi.OnStatisticsData.user_data)
}
inline ::uint64_t OnStatisticsData::_internal_user_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_data_;
}
inline void OnStatisticsData::_internal_set_user_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = value;
}

// -------------------------------------------------------------------

// OnProjectManagerData

// uint64 user_data = 1;
inline void OnProjectManagerData::clear_user_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t OnProjectManagerData::user_data() const {
  // @@protoc_insertion_point(field_get:octaneapi.OnProjectManagerData.user_data)
  return _internal_user_data();
}
inline void OnProjectManagerData::set_user_data(::uint64_t value) {
  _internal_set_user_data(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:octaneapi.OnProjectManagerData.user_data)
}
inline ::uint64_t OnProjectManagerData::_internal_user_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_data_;
}
inline void OnProjectManagerData::_internal_set_user_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = value;
}

// -------------------------------------------------------------------

// StreamCallbackRequest

// .octaneapi.OnNewImageData newImage = 10;
inline bool StreamCallbackRequest::has_newimage() const {
  return payload_case() == kNewImage;
}
inline bool StreamCallbackRequest::_internal_has_newimage() const {
  return payload_case() == kNewImage;
}
inline void StreamCallbackRequest::set_has_newimage() {
  _impl_._oneof_case_[0] = kNewImage;
}
inline void StreamCallbackRequest::clear_newimage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kNewImage) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.newimage_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.newimage_);
    }
    clear_has_payload();
  }
}
inline ::octaneapi::OnNewImageData* PROTOBUF_NULLABLE StreamCallbackRequest::release_newimage() {
  // @@protoc_insertion_point(field_release:octaneapi.StreamCallbackRequest.newImage)
  if (payload_case() == kNewImage) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnNewImageData*>(_impl_.payload_.newimage_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.newimage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::octaneapi::OnNewImageData& StreamCallbackRequest::_internal_newimage() const {
  return payload_case() == kNewImage ? *reinterpret_cast<::octaneapi::OnNewImageData*>(_impl_.payload_.newimage_) : reinterpret_cast<::octaneapi::OnNewImageData&>(::octaneapi::_OnNewImageData_default_instance_);
}
inline const ::octaneapi::OnNewImageData& StreamCallbackRequest::newimage() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.StreamCallbackRequest.newImage)
  return _internal_newimage();
}
inline ::octaneapi::OnNewImageData* PROTOBUF_NULLABLE StreamCallbackRequest::unsafe_arena_release_newimage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:octaneapi.StreamCallbackRequest.newImage)
  if (payload_case() == kNewImage) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnNewImageData*>(_impl_.payload_.newimage_);
    _impl_.payload_.newimage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StreamCallbackRequest::unsafe_arena_set_allocated_newimage(
    ::octaneapi::OnNewImageData* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_newimage();
    _impl_.payload_.newimage_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.StreamCallbackRequest.newImage)
}
inline ::octaneapi::OnNewImageData* PROTOBUF_NONNULL StreamCallbackRequest::_internal_mutable_newimage() {
  if (payload_case() != kNewImage) {
    clear_payload();
    set_has_newimage();
    _impl_.payload_.newimage_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::octaneapi::OnNewImageData>(GetArena()));
  }
  return reinterpret_cast<::octaneapi::OnNewImageData*>(_impl_.payload_.newimage_);
}
inline ::octaneapi::OnNewImageData* PROTOBUF_NONNULL StreamCallbackRequest::mutable_newimage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::octaneapi::OnNewImageData* _msg = _internal_mutable_newimage();
  // @@protoc_insertion_point(field_mutable:octaneapi.StreamCallbackRequest.newImage)
  return _msg;
}

// .octaneapi.OnRenderFailureData renderFailure = 11;
inline bool StreamCallbackRequest::has_renderfailure() const {
  return payload_case() == kRenderFailure;
}
inline bool StreamCallbackRequest::_internal_has_renderfailure() const {
  return payload_case() == kRenderFailure;
}
inline void StreamCallbackRequest::set_has_renderfailure() {
  _impl_._oneof_case_[0] = kRenderFailure;
}
inline void StreamCallbackRequest::clear_renderfailure() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kRenderFailure) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.renderfailure_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.renderfailure_);
    }
    clear_has_payload();
  }
}
inline ::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE StreamCallbackRequest::release_renderfailure() {
  // @@protoc_insertion_point(field_release:octaneapi.StreamCallbackRequest.renderFailure)
  if (payload_case() == kRenderFailure) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnRenderFailureData*>(_impl_.payload_.renderfailure_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.renderfailure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::octaneapi::OnRenderFailureData& StreamCallbackRequest::_internal_renderfailure() const {
  return payload_case() == kRenderFailure ? *reinterpret_cast<::octaneapi::OnRenderFailureData*>(_impl_.payload_.renderfailure_) : reinterpret_cast<::octaneapi::OnRenderFailureData&>(::octaneapi::_OnRenderFailureData_default_instance_);
}
inline const ::octaneapi::OnRenderFailureData& StreamCallbackRequest::renderfailure() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.StreamCallbackRequest.renderFailure)
  return _internal_renderfailure();
}
inline ::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE StreamCallbackRequest::unsafe_arena_release_renderfailure() {
  // @@protoc_insertion_point(field_unsafe_arena_release:octaneapi.StreamCallbackRequest.renderFailure)
  if (payload_case() == kRenderFailure) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnRenderFailureData*>(_impl_.payload_.renderfailure_);
    _impl_.payload_.renderfailure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StreamCallbackRequest::unsafe_arena_set_allocated_renderfailure(
    ::octaneapi::OnRenderFailureData* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_renderfailure();
    _impl_.payload_.renderfailure_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.StreamCallbackRequest.renderFailure)
}
inline ::octaneapi::OnRenderFailureData* PROTOBUF_NONNULL StreamCallbackRequest::_internal_mutable_renderfailure() {
  if (payload_case() != kRenderFailure) {
    clear_payload();
    set_has_renderfailure();
    _impl_.payload_.renderfailure_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::octaneapi::OnRenderFailureData>(GetArena()));
  }
  return reinterpret_cast<::octaneapi::OnRenderFailureData*>(_impl_.payload_.renderfailure_);
}
inline ::octaneapi::OnRenderFailureData* PROTOBUF_NONNULL StreamCallbackRequest::mutable_renderfailure()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::octaneapi::OnRenderFailureData* _msg = _internal_mutable_renderfailure();
  // @@protoc_insertion_point(field_mutable:octaneapi.StreamCallbackRequest.renderFailure)
  return _msg;
}

// .octaneapi.OnStatisticsData newStatistics = 12;
inline bool StreamCallbackRequest::has_newstatistics() const {
  return payload_case() == kNewStatistics;
}
inline bool StreamCallbackRequest::_internal_has_newstatistics() const {
  return payload_case() == kNewStatistics;
}
inline void StreamCallbackRequest::set_has_newstatistics() {
  _impl_._oneof_case_[0] = kNewStatistics;
}
inline void StreamCallbackRequest::clear_newstatistics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kNewStatistics) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.newstatistics_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.newstatistics_);
    }
    clear_has_payload();
  }
}
inline ::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE StreamCallbackRequest::release_newstatistics() {
  // @@protoc_insertion_point(field_release:octaneapi.StreamCallbackRequest.newStatistics)
  if (payload_case() == kNewStatistics) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnStatisticsData*>(_impl_.payload_.newstatistics_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.newstatistics_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::octaneapi::OnStatisticsData& StreamCallbackRequest::_internal_newstatistics() const {
  return payload_case() == kNewStatistics ? *reinterpret_cast<::octaneapi::OnStatisticsData*>(_impl_.payload_.newstatistics_) : reinterpret_cast<::octaneapi::OnStatisticsData&>(::octaneapi::_OnStatisticsData_default_instance_);
}
inline const ::octaneapi::OnStatisticsData& StreamCallbackRequest::newstatistics() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.StreamCallbackRequest.newStatistics)
  return _internal_newstatistics();
}
inline ::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE StreamCallbackRequest::unsafe_arena_release_newstatistics() {
  // @@protoc_insertion_point(field_unsafe_arena_release:octaneapi.StreamCallbackRequest.newStatistics)
  if (payload_case() == kNewStatistics) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnStatisticsData*>(_impl_.payload_.newstatistics_);
    _impl_.payload_.newstatistics_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StreamCallbackRequest::unsafe_arena_set_allocated_newstatistics(
    ::octaneapi::OnStatisticsData* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_newstatistics();
    _impl_.payload_.newstatistics_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.StreamCallbackRequest.newStatistics)
}
inline ::octaneapi::OnStatisticsData* PROTOBUF_NONNULL StreamCallbackRequest::_internal_mutable_newstatistics() {
  if (payload_case() != kNewStatistics) {
    clear_payload();
    set_has_newstatistics();
    _impl_.payload_.newstatistics_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::octaneapi::OnStatisticsData>(GetArena()));
  }
  return reinterpret_cast<::octaneapi::OnStatisticsData*>(_impl_.payload_.newstatistics_);
}
inline ::octaneapi::OnStatisticsData* PROTOBUF_NONNULL StreamCallbackRequest::mutable_newstatistics()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::octaneapi::OnStatisticsData* _msg = _internal_mutable_newstatistics();
  // @@protoc_insertion_point(field_mutable:octaneapi.StreamCallbackRequest.newStatistics)
  return _msg;
}

// .octaneapi.OnProjectManagerData projectManagerChanged = 13;
inline bool StreamCallbackRequest::has_projectmanagerchanged() const {
  return payload_case() == kProjectManagerChanged;
}
inline bool StreamCallbackRequest::_internal_has_projectmanagerchanged() const {
  return payload_case() == kProjectManagerChanged;
}
inline void StreamCallbackRequest::set_has_projectmanagerchanged() {
  _impl_._oneof_case_[0] = kProjectManagerChanged;
}
inline void StreamCallbackRequest::clear_projectmanagerchanged() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kProjectManagerChanged) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.projectmanagerchanged_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.projectmanagerchanged_);
    }
    clear_has_payload();
  }
}
inline ::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE StreamCallbackRequest::release_projectmanagerchanged() {
  // @@protoc_insertion_point(field_release:octaneapi.StreamCallbackRequest.projectManagerChanged)
  if (payload_case() == kProjectManagerChanged) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnProjectManagerData*>(_impl_.payload_.projectmanagerchanged_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.projectmanagerchanged_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::octaneapi::OnProjectManagerData& StreamCallbackRequest::_internal_projectmanagerchanged() const {
  return payload_case() == kProjectManagerChanged ? *reinterpret_cast<::octaneapi::OnProjectManagerData*>(_impl_.payload_.projectmanagerchanged_) : reinterpret_cast<::octaneapi::OnProjectManagerData&>(::octaneapi::_OnProjectManagerData_default_instance_);
}
inline const ::octaneapi::OnProjectManagerData& StreamCallbackRequest::projectmanagerchanged() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:octaneapi.StreamCallbackRequest.projectManagerChanged)
  return _internal_projectmanagerchanged();
}
inline ::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE StreamCallbackRequest::unsafe_arena_release_projectmanagerchanged() {
  // @@protoc_insertion_point(field_unsafe_arena_release:octaneapi.StreamCallbackRequest.projectManagerChanged)
  if (payload_case() == kProjectManagerChanged) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::octaneapi::OnProjectManagerData*>(_impl_.payload_.projectmanagerchanged_);
    _impl_.payload_.projectmanagerchanged_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StreamCallbackRequest::unsafe_arena_set_allocated_projectmanagerchanged(
    ::octaneapi::OnProjectManagerData* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_projectmanagerchanged();
    _impl_.payload_.projectmanagerchanged_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:octaneapi.StreamCallbackRequest.projectManagerChanged)
}
inline ::octaneapi::OnProjectManagerData* PROTOBUF_NONNULL StreamCallbackRequest::_internal_mutable_projectmanagerchanged() {
  if (payload_case() != kProjectManagerChanged) {
    clear_payload();
    set_has_projectmanagerchanged();
    _impl_.payload_.projectmanagerchanged_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::octaneapi::OnProjectManagerData>(GetArena()));
  }
  return reinterpret_cast<::octaneapi::OnProjectManagerData*>(_impl_.payload_.projectmanagerchanged_);
}
inline ::octaneapi::OnProjectManagerData* PROTOBUF_NONNULL StreamCallbackRequest::mutable_projectmanagerchanged()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::octaneapi::OnProjectManagerData* _msg = _internal_mutable_projectmanagerchanged();
  // @@protoc_insertion_point(field_mutable:octaneapi.StreamCallbackRequest.projectManagerChanged)
  return _msg;
}

inline bool StreamCallbackRequest::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void StreamCallbackRequest::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline StreamCallbackRequest::PayloadCase StreamCallbackRequest::payload_case() const {
  return StreamCallbackRequest::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// OnNewRenderedImageRequest

// uint64 user_data = 1;
inline void OnNewRenderedImageRequest::clear_user_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t OnNewRenderedImageRequest::user_data() const {
  // @@protoc_insertion_point(field_get:octaneapi.OnNewRenderedImageRequest.user_data)
  return _internal_user_data();
}
inline void OnNewRenderedImageRequest::set_user_data(::uint64_t value) {
  _internal_set_user_data(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:octaneapi.OnNewRenderedImageRequest.user_data)
}
inline ::uint64_t OnNewRenderedImageRequest::_internal_user_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_data_;
}
inline void OnNewRenderedImageRequest::_internal_set_user_data(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_data_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace octaneapi


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // callbackstream_2eproto_2epb_2eh
